version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    steps:
      - checkout
      - restore_cache:
          key: 'neos-slick-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: 'neos-slick-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn build:production
      - run: npm run semantic-release

workflows:
  version: 2
  tests:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
              - /release-.*/
